<?php $icons = array();
$icons['icomoon-font-awesome-14x14']['glass'] = array("class"=>'glass',"tags"=>'glass',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['music'] = array("class"=>'music',"tags"=>'music',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['search'] = array("class"=>'search',"tags"=>'search',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envelope-o'] = array("class"=>'envelope-o',"tags"=>'envelope-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['heart'] = array("class"=>'heart',"tags"=>'heart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['star'] = array("class"=>'star',"tags"=>'star',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['star-o'] = array("class"=>'star-o',"tags"=>'star-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user'] = array("class"=>'user',"tags"=>'user',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['film'] = array("class"=>'film',"tags"=>'film',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['th-large'] = array("class"=>'th-large',"tags"=>'th-large',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['th'] = array("class"=>'th',"tags"=>'th',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['th-list'] = array("class"=>'th-list',"tags"=>'th-list',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['check'] = array("class"=>'check',"tags"=>'check',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['close, remove, times'] = array("class"=>'close remove times',"tags"=>'close,remove,times',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['search-plus'] = array("class"=>'search-plus',"tags"=>'search-plus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['search-minus'] = array("class"=>'search-minus',"tags"=>'search-minus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['power-off'] = array("class"=>'power-off',"tags"=>'power-off',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['signal'] = array("class"=>'signal',"tags"=>'signal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cog, gear'] = array("class"=>'cog gear',"tags"=>'cog,gear',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['trash-o'] = array("class"=>'trash-o',"tags"=>'trash-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['home'] = array("class"=>'home',"tags"=>'home',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-o'] = array("class"=>'file-o',"tags"=>'file-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['clock-o'] = array("class"=>'clock-o',"tags"=>'clock-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['road'] = array("class"=>'road',"tags"=>'road',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['download'] = array("class"=>'download',"tags"=>'download',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-o-down'] = array("class"=>'arrow-circle-o-down',"tags"=>'arrow-circle-o-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-o-up'] = array("class"=>'arrow-circle-o-up',"tags"=>'arrow-circle-o-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['inbox'] = array("class"=>'inbox',"tags"=>'inbox',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['play-circle-o'] = array("class"=>'play-circle-o',"tags"=>'play-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['repeat, rotate-right'] = array("class"=>'repeat rotate-right',"tags"=>'repeat,rotate-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['refresh'] = array("class"=>'refresh',"tags"=>'refresh',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['list-alt'] = array("class"=>'list-alt',"tags"=>'list-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['lock'] = array("class"=>'lock',"tags"=>'lock',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['flag'] = array("class"=>'flag',"tags"=>'flag',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['headphones'] = array("class"=>'headphones',"tags"=>'headphones',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['volume-off'] = array("class"=>'volume-off',"tags"=>'volume-off',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['volume-down'] = array("class"=>'volume-down',"tags"=>'volume-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['volume-up'] = array("class"=>'volume-up',"tags"=>'volume-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['qrcode'] = array("class"=>'qrcode',"tags"=>'qrcode',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['barcode'] = array("class"=>'barcode',"tags"=>'barcode',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tag'] = array("class"=>'tag',"tags"=>'tag',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tags'] = array("class"=>'tags',"tags"=>'tags',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['book'] = array("class"=>'book',"tags"=>'book',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bookmark'] = array("class"=>'bookmark',"tags"=>'bookmark',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['print'] = array("class"=>'print',"tags"=>'print',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['camera'] = array("class"=>'camera',"tags"=>'camera',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['font'] = array("class"=>'font',"tags"=>'font',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bold'] = array("class"=>'bold',"tags"=>'bold',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['italic'] = array("class"=>'italic',"tags"=>'italic',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['text-height'] = array("class"=>'text-height',"tags"=>'text-height',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['text-width'] = array("class"=>'text-width',"tags"=>'text-width',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['align-left'] = array("class"=>'align-left',"tags"=>'align-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['align-center'] = array("class"=>'align-center',"tags"=>'align-center',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['align-right'] = array("class"=>'align-right',"tags"=>'align-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['align-justify'] = array("class"=>'align-justify',"tags"=>'align-justify',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['list'] = array("class"=>'list',"tags"=>'list',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dedent, outdent'] = array("class"=>'dedent outdent',"tags"=>'dedent,outdent',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['indent'] = array("class"=>'indent',"tags"=>'indent',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['video-camera'] = array("class"=>'video-camera',"tags"=>'video-camera',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['image, photo, picture-o'] = array("class"=>'image photo picture-o',"tags"=>'image,photo,picture-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pencil'] = array("class"=>'pencil',"tags"=>'pencil',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['map-marker'] = array("class"=>'map-marker',"tags"=>'map-marker',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['adjust'] = array("class"=>'adjust',"tags"=>'adjust',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tint'] = array("class"=>'tint',"tags"=>'tint',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['edit, pencil-square-o'] = array("class"=>'edit pencil-square-o',"tags"=>'edit,pencil-square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['share-square-o'] = array("class"=>'share-square-o',"tags"=>'share-square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['check-square-o'] = array("class"=>'check-square-o',"tags"=>'check-square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrows'] = array("class"=>'arrows',"tags"=>'arrows',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['step-backward'] = array("class"=>'step-backward',"tags"=>'step-backward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fast-backward'] = array("class"=>'fast-backward',"tags"=>'fast-backward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['backward'] = array("class"=>'backward',"tags"=>'backward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['play'] = array("class"=>'play',"tags"=>'play',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pause'] = array("class"=>'pause',"tags"=>'pause',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stop'] = array("class"=>'stop',"tags"=>'stop',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['forward'] = array("class"=>'forward',"tags"=>'forward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fast-forward'] = array("class"=>'fast-forward',"tags"=>'fast-forward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['step-forward'] = array("class"=>'step-forward',"tags"=>'step-forward',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eject'] = array("class"=>'eject',"tags"=>'eject',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-left'] = array("class"=>'chevron-left',"tags"=>'chevron-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-right'] = array("class"=>'chevron-right',"tags"=>'chevron-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plus-circle'] = array("class"=>'plus-circle',"tags"=>'plus-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['minus-circle'] = array("class"=>'minus-circle',"tags"=>'minus-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['times-circle'] = array("class"=>'times-circle',"tags"=>'times-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['check-circle'] = array("class"=>'check-circle',"tags"=>'check-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['question-circle'] = array("class"=>'question-circle',"tags"=>'question-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['info-circle'] = array("class"=>'info-circle',"tags"=>'info-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['crosshairs'] = array("class"=>'crosshairs',"tags"=>'crosshairs',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['times-circle-o'] = array("class"=>'times-circle-o',"tags"=>'times-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['check-circle-o'] = array("class"=>'check-circle-o',"tags"=>'check-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ban'] = array("class"=>'ban',"tags"=>'ban',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-left'] = array("class"=>'arrow-left',"tags"=>'arrow-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-right'] = array("class"=>'arrow-right',"tags"=>'arrow-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-up'] = array("class"=>'arrow-up',"tags"=>'arrow-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-down'] = array("class"=>'arrow-down',"tags"=>'arrow-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mail-forward, share'] = array("class"=>'mail-forward share',"tags"=>'mail-forward,share',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['expand'] = array("class"=>'expand',"tags"=>'expand',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['compress'] = array("class"=>'compress',"tags"=>'compress',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plus'] = array("class"=>'plus',"tags"=>'plus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['minus'] = array("class"=>'minus',"tags"=>'minus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['asterisk'] = array("class"=>'asterisk',"tags"=>'asterisk',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['exclamation-circle'] = array("class"=>'exclamation-circle',"tags"=>'exclamation-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gift'] = array("class"=>'gift',"tags"=>'gift',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['leaf'] = array("class"=>'leaf',"tags"=>'leaf',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fire'] = array("class"=>'fire',"tags"=>'fire',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eye'] = array("class"=>'eye',"tags"=>'eye',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eye-slash'] = array("class"=>'eye-slash',"tags"=>'eye-slash',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['exclamation-triangle, warning'] = array("class"=>'exclamation-triangle warning',"tags"=>'exclamation-triangle,warning',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plane'] = array("class"=>'plane',"tags"=>'plane',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar'] = array("class"=>'calendar',"tags"=>'calendar',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['random'] = array("class"=>'random',"tags"=>'random',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['comment'] = array("class"=>'comment',"tags"=>'comment',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['magnet'] = array("class"=>'magnet',"tags"=>'magnet',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-up'] = array("class"=>'chevron-up',"tags"=>'chevron-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-down'] = array("class"=>'chevron-down',"tags"=>'chevron-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['retweet'] = array("class"=>'retweet',"tags"=>'retweet',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shopping-cart'] = array("class"=>'shopping-cart',"tags"=>'shopping-cart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['folder'] = array("class"=>'folder',"tags"=>'folder',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['folder-open'] = array("class"=>'folder-open',"tags"=>'folder-open',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrows-v'] = array("class"=>'arrows-v',"tags"=>'arrows-v',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrows-h'] = array("class"=>'arrows-h',"tags"=>'arrows-h',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bar-chart, bar-chart-o'] = array("class"=>'bar-chart bar-chart-o',"tags"=>'bar-chart,bar-chart-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['twitter-square'] = array("class"=>'twitter-square',"tags"=>'twitter-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['facebook-square'] = array("class"=>'facebook-square',"tags"=>'facebook-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['camera-retro'] = array("class"=>'camera-retro',"tags"=>'camera-retro',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['key'] = array("class"=>'key',"tags"=>'key',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cogs, gears'] = array("class"=>'cogs gears',"tags"=>'cogs,gears',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['comments'] = array("class"=>'comments',"tags"=>'comments',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thumbs-o-up'] = array("class"=>'thumbs-o-up',"tags"=>'thumbs-o-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thumbs-o-down'] = array("class"=>'thumbs-o-down',"tags"=>'thumbs-o-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['star-half'] = array("class"=>'star-half',"tags"=>'star-half',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['heart-o'] = array("class"=>'heart-o',"tags"=>'heart-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sign-out'] = array("class"=>'sign-out',"tags"=>'sign-out',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['linkedin-square'] = array("class"=>'linkedin-square',"tags"=>'linkedin-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thumb-tack'] = array("class"=>'thumb-tack',"tags"=>'thumb-tack',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['external-link'] = array("class"=>'external-link',"tags"=>'external-link',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sign-in'] = array("class"=>'sign-in',"tags"=>'sign-in',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['trophy'] = array("class"=>'trophy',"tags"=>'trophy',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['github-square'] = array("class"=>'github-square',"tags"=>'github-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['upload'] = array("class"=>'upload',"tags"=>'upload',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['lemon-o'] = array("class"=>'lemon-o',"tags"=>'lemon-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['phone'] = array("class"=>'phone',"tags"=>'phone',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['square-o'] = array("class"=>'square-o',"tags"=>'square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bookmark-o'] = array("class"=>'bookmark-o',"tags"=>'bookmark-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['phone-square'] = array("class"=>'phone-square',"tags"=>'phone-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['twitter'] = array("class"=>'twitter',"tags"=>'twitter',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['facebook, facebook-f'] = array("class"=>'facebook facebook-f',"tags"=>'facebook,facebook-f',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['github'] = array("class"=>'github',"tags"=>'github',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['unlock'] = array("class"=>'unlock',"tags"=>'unlock',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['credit-card'] = array("class"=>'credit-card',"tags"=>'credit-card',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['feed, rss'] = array("class"=>'feed rss',"tags"=>'feed,rss',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hdd-o'] = array("class"=>'hdd-o',"tags"=>'hdd-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bullhorn'] = array("class"=>'bullhorn',"tags"=>'bullhorn',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bell-o'] = array("class"=>'bell-o',"tags"=>'bell-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['certificate'] = array("class"=>'certificate',"tags"=>'certificate',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-o-right'] = array("class"=>'hand-o-right',"tags"=>'hand-o-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-o-left'] = array("class"=>'hand-o-left',"tags"=>'hand-o-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-o-up'] = array("class"=>'hand-o-up',"tags"=>'hand-o-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-o-down'] = array("class"=>'hand-o-down',"tags"=>'hand-o-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-left'] = array("class"=>'arrow-circle-left',"tags"=>'arrow-circle-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-right'] = array("class"=>'arrow-circle-right',"tags"=>'arrow-circle-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-up'] = array("class"=>'arrow-circle-up',"tags"=>'arrow-circle-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-down'] = array("class"=>'arrow-circle-down',"tags"=>'arrow-circle-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['globe'] = array("class"=>'globe',"tags"=>'globe',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wrench'] = array("class"=>'wrench',"tags"=>'wrench',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tasks'] = array("class"=>'tasks',"tags"=>'tasks',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['filter'] = array("class"=>'filter',"tags"=>'filter',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['briefcase'] = array("class"=>'briefcase',"tags"=>'briefcase',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrows-alt'] = array("class"=>'arrows-alt',"tags"=>'arrows-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['group, users'] = array("class"=>'group users',"tags"=>'group,users',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chain, link'] = array("class"=>'chain link',"tags"=>'chain,link',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cloud'] = array("class"=>'cloud',"tags"=>'cloud',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['flask'] = array("class"=>'flask',"tags"=>'flask',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cut, scissors'] = array("class"=>'cut scissors',"tags"=>'cut,scissors',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['copy, files-o'] = array("class"=>'copy files-o',"tags"=>'copy,files-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paperclip'] = array("class"=>'paperclip',"tags"=>'paperclip',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['floppy-o, save'] = array("class"=>'floppy-o save',"tags"=>'floppy-o,save',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['square'] = array("class"=>'square',"tags"=>'square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bars, navicon, reorder'] = array("class"=>'bars navicon reorder',"tags"=>'bars,navicon,reorder',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['list-ul'] = array("class"=>'list-ul',"tags"=>'list-ul',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['list-ol'] = array("class"=>'list-ol',"tags"=>'list-ol',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['strikethrough'] = array("class"=>'strikethrough',"tags"=>'strikethrough',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['underline'] = array("class"=>'underline',"tags"=>'underline',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['table'] = array("class"=>'table',"tags"=>'table',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['magic'] = array("class"=>'magic',"tags"=>'magic',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['truck'] = array("class"=>'truck',"tags"=>'truck',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pinterest'] = array("class"=>'pinterest',"tags"=>'pinterest',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pinterest-square'] = array("class"=>'pinterest-square',"tags"=>'pinterest-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['google-plus-square'] = array("class"=>'google-plus-square',"tags"=>'google-plus-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['google-plus'] = array("class"=>'google-plus',"tags"=>'google-plus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['money'] = array("class"=>'money',"tags"=>'money',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-down'] = array("class"=>'caret-down',"tags"=>'caret-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-up'] = array("class"=>'caret-up',"tags"=>'caret-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-left'] = array("class"=>'caret-left',"tags"=>'caret-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-right'] = array("class"=>'caret-right',"tags"=>'caret-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['columns'] = array("class"=>'columns',"tags"=>'columns',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort, unsorted'] = array("class"=>'sort unsorted',"tags"=>'sort,unsorted',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-desc, sort-down'] = array("class"=>'sort-desc sort-down',"tags"=>'sort-desc,sort-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-asc, sort-up'] = array("class"=>'sort-asc sort-up',"tags"=>'sort-asc,sort-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envelope'] = array("class"=>'envelope',"tags"=>'envelope',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['linkedin'] = array("class"=>'linkedin',"tags"=>'linkedin',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['rotate-left, undo'] = array("class"=>'rotate-left undo',"tags"=>'rotate-left,undo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gavel, legal'] = array("class"=>'gavel legal',"tags"=>'gavel,legal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dashboard, tachometer'] = array("class"=>'dashboard tachometer',"tags"=>'dashboard,tachometer',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['comment-o'] = array("class"=>'comment-o',"tags"=>'comment-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['comments-o'] = array("class"=>'comments-o',"tags"=>'comments-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bolt, flash'] = array("class"=>'bolt flash',"tags"=>'bolt,flash',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sitemap'] = array("class"=>'sitemap',"tags"=>'sitemap',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['umbrella'] = array("class"=>'umbrella',"tags"=>'umbrella',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['clipboard, paste'] = array("class"=>'clipboard paste',"tags"=>'clipboard,paste',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['lightbulb-o'] = array("class"=>'lightbulb-o',"tags"=>'lightbulb-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['exchange'] = array("class"=>'exchange',"tags"=>'exchange',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cloud-download'] = array("class"=>'cloud-download',"tags"=>'cloud-download',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cloud-upload'] = array("class"=>'cloud-upload',"tags"=>'cloud-upload',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-md'] = array("class"=>'user-md',"tags"=>'user-md',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stethoscope'] = array("class"=>'stethoscope',"tags"=>'stethoscope',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['suitcase'] = array("class"=>'suitcase',"tags"=>'suitcase',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bell'] = array("class"=>'bell',"tags"=>'bell',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['coffee'] = array("class"=>'coffee',"tags"=>'coffee',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cutlery'] = array("class"=>'cutlery',"tags"=>'cutlery',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-text-o'] = array("class"=>'file-text-o',"tags"=>'file-text-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['building-o'] = array("class"=>'building-o',"tags"=>'building-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hospital-o'] = array("class"=>'hospital-o',"tags"=>'hospital-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ambulance'] = array("class"=>'ambulance',"tags"=>'ambulance',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['medkit'] = array("class"=>'medkit',"tags"=>'medkit',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fighter-jet'] = array("class"=>'fighter-jet',"tags"=>'fighter-jet',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['beer'] = array("class"=>'beer',"tags"=>'beer',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['h-square'] = array("class"=>'h-square',"tags"=>'h-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plus-square'] = array("class"=>'plus-square',"tags"=>'plus-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-double-left'] = array("class"=>'angle-double-left',"tags"=>'angle-double-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-double-right'] = array("class"=>'angle-double-right',"tags"=>'angle-double-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-double-up'] = array("class"=>'angle-double-up',"tags"=>'angle-double-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-double-down'] = array("class"=>'angle-double-down',"tags"=>'angle-double-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-left'] = array("class"=>'angle-left',"tags"=>'angle-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-right'] = array("class"=>'angle-right',"tags"=>'angle-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-up'] = array("class"=>'angle-up',"tags"=>'angle-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angle-down'] = array("class"=>'angle-down',"tags"=>'angle-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['desktop'] = array("class"=>'desktop',"tags"=>'desktop',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['laptop'] = array("class"=>'laptop',"tags"=>'laptop',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tablet'] = array("class"=>'tablet',"tags"=>'tablet',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mobile, mobile-phone'] = array("class"=>'mobile mobile-phone',"tags"=>'mobile,mobile-phone',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['circle-o'] = array("class"=>'circle-o',"tags"=>'circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['quote-left'] = array("class"=>'quote-left',"tags"=>'quote-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['quote-right'] = array("class"=>'quote-right',"tags"=>'quote-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['spinner'] = array("class"=>'spinner',"tags"=>'spinner',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['circle'] = array("class"=>'circle',"tags"=>'circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mail-reply, reply'] = array("class"=>'mail-reply reply',"tags"=>'mail-reply,reply',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['github-alt'] = array("class"=>'github-alt',"tags"=>'github-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['folder-o'] = array("class"=>'folder-o',"tags"=>'folder-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['folder-open-o'] = array("class"=>'folder-open-o',"tags"=>'folder-open-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['smile-o'] = array("class"=>'smile-o',"tags"=>'smile-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['frown-o'] = array("class"=>'frown-o',"tags"=>'frown-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['meh-o'] = array("class"=>'meh-o',"tags"=>'meh-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gamepad'] = array("class"=>'gamepad',"tags"=>'gamepad',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['keyboard-o'] = array("class"=>'keyboard-o',"tags"=>'keyboard-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['flag-o'] = array("class"=>'flag-o',"tags"=>'flag-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['flag-checkered'] = array("class"=>'flag-checkered',"tags"=>'flag-checkered',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['terminal'] = array("class"=>'terminal',"tags"=>'terminal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['code'] = array("class"=>'code',"tags"=>'code',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mail-reply-all, reply-all'] = array("class"=>'mail-reply-all reply-all',"tags"=>'mail-reply-all,reply-all',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['star-half-empty, star-half-full, star-half-o'] = array("class"=>'star-half-empty star-half-full star-half-o',"tags"=>'star-half-empty,star-half-full,star-half-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['location-arrow'] = array("class"=>'location-arrow',"tags"=>'location-arrow',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['crop'] = array("class"=>'crop',"tags"=>'crop',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['code-fork'] = array("class"=>'code-fork',"tags"=>'code-fork',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chain-broken, unlink'] = array("class"=>'chain-broken unlink',"tags"=>'chain-broken,unlink',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['question'] = array("class"=>'question',"tags"=>'question',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['info'] = array("class"=>'info',"tags"=>'info',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['exclamation'] = array("class"=>'exclamation',"tags"=>'exclamation',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['superscript'] = array("class"=>'superscript',"tags"=>'superscript',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['subscript'] = array("class"=>'subscript',"tags"=>'subscript',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eraser'] = array("class"=>'eraser',"tags"=>'eraser',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['puzzle-piece'] = array("class"=>'puzzle-piece',"tags"=>'puzzle-piece',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['microphone'] = array("class"=>'microphone',"tags"=>'microphone',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['microphone-slash'] = array("class"=>'microphone-slash',"tags"=>'microphone-slash',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shield'] = array("class"=>'shield',"tags"=>'shield',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar-o'] = array("class"=>'calendar-o',"tags"=>'calendar-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fire-extinguisher'] = array("class"=>'fire-extinguisher',"tags"=>'fire-extinguisher',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['rocket'] = array("class"=>'rocket',"tags"=>'rocket',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['maxcdn'] = array("class"=>'maxcdn',"tags"=>'maxcdn',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-circle-left'] = array("class"=>'chevron-circle-left',"tags"=>'chevron-circle-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-circle-right'] = array("class"=>'chevron-circle-right',"tags"=>'chevron-circle-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-circle-up'] = array("class"=>'chevron-circle-up',"tags"=>'chevron-circle-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chevron-circle-down'] = array("class"=>'chevron-circle-down',"tags"=>'chevron-circle-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['html5'] = array("class"=>'html5',"tags"=>'html5',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['css3'] = array("class"=>'css3',"tags"=>'css3',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['anchor'] = array("class"=>'anchor',"tags"=>'anchor',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['unlock-alt'] = array("class"=>'unlock-alt',"tags"=>'unlock-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bullseye'] = array("class"=>'bullseye',"tags"=>'bullseye',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ellipsis-h'] = array("class"=>'ellipsis-h',"tags"=>'ellipsis-h',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ellipsis-v'] = array("class"=>'ellipsis-v',"tags"=>'ellipsis-v',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['rss-square'] = array("class"=>'rss-square',"tags"=>'rss-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['play-circle'] = array("class"=>'play-circle',"tags"=>'play-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ticket'] = array("class"=>'ticket',"tags"=>'ticket',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['minus-square'] = array("class"=>'minus-square',"tags"=>'minus-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['minus-square-o'] = array("class"=>'minus-square-o',"tags"=>'minus-square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['level-up'] = array("class"=>'level-up',"tags"=>'level-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['level-down'] = array("class"=>'level-down',"tags"=>'level-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['check-square'] = array("class"=>'check-square',"tags"=>'check-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pencil-square'] = array("class"=>'pencil-square',"tags"=>'pencil-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['external-link-square'] = array("class"=>'external-link-square',"tags"=>'external-link-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['share-square'] = array("class"=>'share-square',"tags"=>'share-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['compass'] = array("class"=>'compass',"tags"=>'compass',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-square-o-down, toggle-down'] = array("class"=>'caret-square-o-down toggle-down',"tags"=>'caret-square-o-down,toggle-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-square-o-up, toggle-up'] = array("class"=>'caret-square-o-up toggle-up',"tags"=>'caret-square-o-up,toggle-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-square-o-right, toggle-right'] = array("class"=>'caret-square-o-right toggle-right',"tags"=>'caret-square-o-right,toggle-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eur, euro'] = array("class"=>'eur euro',"tags"=>'eur,euro',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gbp'] = array("class"=>'gbp',"tags"=>'gbp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dollar, usd'] = array("class"=>'dollar usd',"tags"=>'dollar,usd',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['inr, rupee'] = array("class"=>'inr rupee',"tags"=>'inr,rupee',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cny, jpy, rmb, yen'] = array("class"=>'cny jpy rmb yen',"tags"=>'cny,jpy,rmb,yen',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['rouble, rub, ruble'] = array("class"=>'rouble rub ruble',"tags"=>'rouble,rub,ruble',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['krw, won'] = array("class"=>'krw won',"tags"=>'krw,won',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bitcoin, btc'] = array("class"=>'bitcoin btc',"tags"=>'bitcoin,btc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file'] = array("class"=>'file',"tags"=>'file',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-text'] = array("class"=>'file-text',"tags"=>'file-text',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-alpha-asc'] = array("class"=>'sort-alpha-asc',"tags"=>'sort-alpha-asc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-alpha-desc'] = array("class"=>'sort-alpha-desc',"tags"=>'sort-alpha-desc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-amount-asc'] = array("class"=>'sort-amount-asc',"tags"=>'sort-amount-asc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-amount-desc'] = array("class"=>'sort-amount-desc',"tags"=>'sort-amount-desc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-numeric-asc'] = array("class"=>'sort-numeric-asc',"tags"=>'sort-numeric-asc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sort-numeric-desc'] = array("class"=>'sort-numeric-desc',"tags"=>'sort-numeric-desc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thumbs-up'] = array("class"=>'thumbs-up',"tags"=>'thumbs-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thumbs-down'] = array("class"=>'thumbs-down',"tags"=>'thumbs-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['youtube-square'] = array("class"=>'youtube-square',"tags"=>'youtube-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['youtube'] = array("class"=>'youtube',"tags"=>'youtube',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['xing'] = array("class"=>'xing',"tags"=>'xing',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['xing-square'] = array("class"=>'xing-square',"tags"=>'xing-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['youtube-play'] = array("class"=>'youtube-play',"tags"=>'youtube-play',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dropbox'] = array("class"=>'dropbox',"tags"=>'dropbox',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stack-overflow'] = array("class"=>'stack-overflow',"tags"=>'stack-overflow',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['instagram'] = array("class"=>'instagram',"tags"=>'instagram',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['flickr'] = array("class"=>'flickr',"tags"=>'flickr',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['adn'] = array("class"=>'adn',"tags"=>'adn',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bitbucket'] = array("class"=>'bitbucket',"tags"=>'bitbucket',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bitbucket-square'] = array("class"=>'bitbucket-square',"tags"=>'bitbucket-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tumblr'] = array("class"=>'tumblr',"tags"=>'tumblr',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tumblr-square'] = array("class"=>'tumblr-square',"tags"=>'tumblr-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['long-arrow-down'] = array("class"=>'long-arrow-down',"tags"=>'long-arrow-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['long-arrow-up'] = array("class"=>'long-arrow-up',"tags"=>'long-arrow-up',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['long-arrow-left'] = array("class"=>'long-arrow-left',"tags"=>'long-arrow-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['long-arrow-right'] = array("class"=>'long-arrow-right',"tags"=>'long-arrow-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['apple'] = array("class"=>'apple',"tags"=>'apple',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['windows'] = array("class"=>'windows',"tags"=>'windows',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['android'] = array("class"=>'android',"tags"=>'android',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['linux'] = array("class"=>'linux',"tags"=>'linux',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dribbble'] = array("class"=>'dribbble',"tags"=>'dribbble',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['skype'] = array("class"=>'skype',"tags"=>'skype',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['foursquare'] = array("class"=>'foursquare',"tags"=>'foursquare',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['trello'] = array("class"=>'trello',"tags"=>'trello',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['female'] = array("class"=>'female',"tags"=>'female',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['male'] = array("class"=>'male',"tags"=>'male',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gittip, gratipay'] = array("class"=>'gittip gratipay',"tags"=>'gittip,gratipay',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sun-o'] = array("class"=>'sun-o',"tags"=>'sun-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['moon-o'] = array("class"=>'moon-o',"tags"=>'moon-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['archive'] = array("class"=>'archive',"tags"=>'archive',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bug'] = array("class"=>'bug',"tags"=>'bug',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['vk'] = array("class"=>'vk',"tags"=>'vk',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['weibo'] = array("class"=>'weibo',"tags"=>'weibo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['renren'] = array("class"=>'renren',"tags"=>'renren',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pagelines'] = array("class"=>'pagelines',"tags"=>'pagelines',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stack-exchange'] = array("class"=>'stack-exchange',"tags"=>'stack-exchange',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-o-right'] = array("class"=>'arrow-circle-o-right',"tags"=>'arrow-circle-o-right',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['arrow-circle-o-left'] = array("class"=>'arrow-circle-o-left',"tags"=>'arrow-circle-o-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['caret-square-o-left, toggle-left'] = array("class"=>'caret-square-o-left toggle-left',"tags"=>'caret-square-o-left,toggle-left',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dot-circle-o'] = array("class"=>'dot-circle-o',"tags"=>'dot-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wheelchair'] = array("class"=>'wheelchair',"tags"=>'wheelchair',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['vimeo-square'] = array("class"=>'vimeo-square',"tags"=>'vimeo-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['try, turkish-lira'] = array("class"=>'try turkish-lira',"tags"=>'try,turkish-lira',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plus-square-o'] = array("class"=>'plus-square-o',"tags"=>'plus-square-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['space-shuttle'] = array("class"=>'space-shuttle',"tags"=>'space-shuttle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['slack'] = array("class"=>'slack',"tags"=>'slack',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envelope-square'] = array("class"=>'envelope-square',"tags"=>'envelope-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wordpress'] = array("class"=>'wordpress',"tags"=>'wordpress',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['openid'] = array("class"=>'openid',"tags"=>'openid',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bank, institution, university'] = array("class"=>'bank institution university',"tags"=>'bank,institution,university',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['graduation-cap, mortar-board'] = array("class"=>'graduation-cap mortar-board',"tags"=>'graduation-cap,mortar-board',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['yahoo'] = array("class"=>'yahoo',"tags"=>'yahoo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['google'] = array("class"=>'google',"tags"=>'google',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['reddit'] = array("class"=>'reddit',"tags"=>'reddit',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['reddit-square'] = array("class"=>'reddit-square',"tags"=>'reddit-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stumbleupon-circle'] = array("class"=>'stumbleupon-circle',"tags"=>'stumbleupon-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stumbleupon'] = array("class"=>'stumbleupon',"tags"=>'stumbleupon',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['delicious'] = array("class"=>'delicious',"tags"=>'delicious',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['digg'] = array("class"=>'digg',"tags"=>'digg',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pied-piper-pp'] = array("class"=>'pied-piper-pp',"tags"=>'pied-piper-pp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pied-piper-alt'] = array("class"=>'pied-piper-alt',"tags"=>'pied-piper-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['drupal'] = array("class"=>'drupal',"tags"=>'drupal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['joomla'] = array("class"=>'joomla',"tags"=>'joomla',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['language'] = array("class"=>'language',"tags"=>'language',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fax'] = array("class"=>'fax',"tags"=>'fax',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['building'] = array("class"=>'building',"tags"=>'building',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['child'] = array("class"=>'child',"tags"=>'child',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paw'] = array("class"=>'paw',"tags"=>'paw',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['spoon'] = array("class"=>'spoon',"tags"=>'spoon',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cube'] = array("class"=>'cube',"tags"=>'cube',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cubes'] = array("class"=>'cubes',"tags"=>'cubes',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['behance'] = array("class"=>'behance',"tags"=>'behance',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['behance-square'] = array("class"=>'behance-square',"tags"=>'behance-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['steam'] = array("class"=>'steam',"tags"=>'steam',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['steam-square'] = array("class"=>'steam-square',"tags"=>'steam-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['recycle'] = array("class"=>'recycle',"tags"=>'recycle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['automobile, car'] = array("class"=>'automobile car',"tags"=>'automobile,car',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cab, taxi'] = array("class"=>'cab taxi',"tags"=>'cab,taxi',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tree'] = array("class"=>'tree',"tags"=>'tree',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['spotify'] = array("class"=>'spotify',"tags"=>'spotify',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['deviantart'] = array("class"=>'deviantart',"tags"=>'deviantart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['soundcloud'] = array("class"=>'soundcloud',"tags"=>'soundcloud',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['database'] = array("class"=>'database',"tags"=>'database',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-pdf-o'] = array("class"=>'file-pdf-o',"tags"=>'file-pdf-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-word-o'] = array("class"=>'file-word-o',"tags"=>'file-word-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-excel-o'] = array("class"=>'file-excel-o',"tags"=>'file-excel-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-powerpoint-o'] = array("class"=>'file-powerpoint-o',"tags"=>'file-powerpoint-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-image-o, file-photo-o, file-picture-o'] = array("class"=>'file-image-o file-photo-o file-picture-o',"tags"=>'file-image-o,file-photo-o,file-picture-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-archive-o, file-zip-o'] = array("class"=>'file-archive-o file-zip-o',"tags"=>'file-archive-o,file-zip-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-audio-o, file-sound-o'] = array("class"=>'file-audio-o file-sound-o',"tags"=>'file-audio-o,file-sound-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-movie-o, file-video-o'] = array("class"=>'file-movie-o file-video-o',"tags"=>'file-movie-o,file-video-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['file-code-o'] = array("class"=>'file-code-o',"tags"=>'file-code-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['vine'] = array("class"=>'vine',"tags"=>'vine',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['codepen'] = array("class"=>'codepen',"tags"=>'codepen',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['jsfiddle'] = array("class"=>'jsfiddle',"tags"=>'jsfiddle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['life-bouy, life-buoy, life-ring, life-saver, support'] = array("class"=>'life-bouy life-buoy life-ring life-saver support',"tags"=>'life-bouy,life-buoy,life-ring,life-saver,support',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['circle-o-notch'] = array("class"=>'circle-o-notch',"tags"=>'circle-o-notch',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ra, rebel, resistance'] = array("class"=>'ra rebel resistance',"tags"=>'ra,rebel,resistance',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['empire, ge'] = array("class"=>'empire ge',"tags"=>'empire,ge',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['git-square'] = array("class"=>'git-square',"tags"=>'git-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['git'] = array("class"=>'git',"tags"=>'git',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hacker-news, y-combinator-square, yc-square'] = array("class"=>'hacker-news y-combinator-square yc-square',"tags"=>'hacker-news,y-combinator-square,yc-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tencent-weibo'] = array("class"=>'tencent-weibo',"tags"=>'tencent-weibo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['qq'] = array("class"=>'qq',"tags"=>'qq',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wechat, weixin'] = array("class"=>'wechat weixin',"tags"=>'wechat,weixin',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paper-plane, send'] = array("class"=>'paper-plane send',"tags"=>'paper-plane,send',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paper-plane-o, send-o'] = array("class"=>'paper-plane-o send-o',"tags"=>'paper-plane-o,send-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['history'] = array("class"=>'history',"tags"=>'history',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['circle-thin'] = array("class"=>'circle-thin',"tags"=>'circle-thin',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['header'] = array("class"=>'header',"tags"=>'header',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paragraph'] = array("class"=>'paragraph',"tags"=>'paragraph',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sliders'] = array("class"=>'sliders',"tags"=>'sliders',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['share-alt'] = array("class"=>'share-alt',"tags"=>'share-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['share-alt-square'] = array("class"=>'share-alt-square',"tags"=>'share-alt-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bomb'] = array("class"=>'bomb',"tags"=>'bomb',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['futbol-o, soccer-ball-o'] = array("class"=>'futbol-o soccer-ball-o',"tags"=>'futbol-o,soccer-ball-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tty'] = array("class"=>'tty',"tags"=>'tty',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['binoculars'] = array("class"=>'binoculars',"tags"=>'binoculars',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['plug'] = array("class"=>'plug',"tags"=>'plug',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['slideshare'] = array("class"=>'slideshare',"tags"=>'slideshare',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['twitch'] = array("class"=>'twitch',"tags"=>'twitch',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['yelp'] = array("class"=>'yelp',"tags"=>'yelp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['newspaper-o'] = array("class"=>'newspaper-o',"tags"=>'newspaper-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wifi'] = array("class"=>'wifi',"tags"=>'wifi',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calculator'] = array("class"=>'calculator',"tags"=>'calculator',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paypal'] = array("class"=>'paypal',"tags"=>'paypal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['google-wallet'] = array("class"=>'google-wallet',"tags"=>'google-wallet',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-visa'] = array("class"=>'cc-visa',"tags"=>'cc-visa',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-mastercard'] = array("class"=>'cc-mastercard',"tags"=>'cc-mastercard',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-discover'] = array("class"=>'cc-discover',"tags"=>'cc-discover',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-amex'] = array("class"=>'cc-amex',"tags"=>'cc-amex',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-paypal'] = array("class"=>'cc-paypal',"tags"=>'cc-paypal',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-stripe'] = array("class"=>'cc-stripe',"tags"=>'cc-stripe',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bell-slash'] = array("class"=>'bell-slash',"tags"=>'bell-slash',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bell-slash-o'] = array("class"=>'bell-slash-o',"tags"=>'bell-slash-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['trash'] = array("class"=>'trash',"tags"=>'trash',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['copyright'] = array("class"=>'copyright',"tags"=>'copyright',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['at'] = array("class"=>'at',"tags"=>'at',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eyedropper'] = array("class"=>'eyedropper',"tags"=>'eyedropper',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['paint-brush'] = array("class"=>'paint-brush',"tags"=>'paint-brush',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['birthday-cake'] = array("class"=>'birthday-cake',"tags"=>'birthday-cake',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['area-chart'] = array("class"=>'area-chart',"tags"=>'area-chart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pie-chart'] = array("class"=>'pie-chart',"tags"=>'pie-chart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['line-chart'] = array("class"=>'line-chart',"tags"=>'line-chart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['lastfm'] = array("class"=>'lastfm',"tags"=>'lastfm',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['lastfm-square'] = array("class"=>'lastfm-square',"tags"=>'lastfm-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['toggle-off'] = array("class"=>'toggle-off',"tags"=>'toggle-off',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['toggle-on'] = array("class"=>'toggle-on',"tags"=>'toggle-on',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bicycle'] = array("class"=>'bicycle',"tags"=>'bicycle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bus'] = array("class"=>'bus',"tags"=>'bus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ioxhost'] = array("class"=>'ioxhost',"tags"=>'ioxhost',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['angellist'] = array("class"=>'angellist',"tags"=>'angellist',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc'] = array("class"=>'cc',"tags"=>'cc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ils, shekel, sheqel'] = array("class"=>'ils shekel sheqel',"tags"=>'ils,shekel,sheqel',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['meanpath'] = array("class"=>'meanpath',"tags"=>'meanpath',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['buysellads'] = array("class"=>'buysellads',"tags"=>'buysellads',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['connectdevelop'] = array("class"=>'connectdevelop',"tags"=>'connectdevelop',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['dashcube'] = array("class"=>'dashcube',"tags"=>'dashcube',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['forumbee'] = array("class"=>'forumbee',"tags"=>'forumbee',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['leanpub'] = array("class"=>'leanpub',"tags"=>'leanpub',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sellsy'] = array("class"=>'sellsy',"tags"=>'sellsy',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shirtsinbulk'] = array("class"=>'shirtsinbulk',"tags"=>'shirtsinbulk',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['simplybuilt'] = array("class"=>'simplybuilt',"tags"=>'simplybuilt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['skyatlas'] = array("class"=>'skyatlas',"tags"=>'skyatlas',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cart-plus'] = array("class"=>'cart-plus',"tags"=>'cart-plus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cart-arrow-down'] = array("class"=>'cart-arrow-down',"tags"=>'cart-arrow-down',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['diamond'] = array("class"=>'diamond',"tags"=>'diamond',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ship'] = array("class"=>'ship',"tags"=>'ship',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-secret'] = array("class"=>'user-secret',"tags"=>'user-secret',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['motorcycle'] = array("class"=>'motorcycle',"tags"=>'motorcycle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['street-view'] = array("class"=>'street-view',"tags"=>'street-view',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['heartbeat'] = array("class"=>'heartbeat',"tags"=>'heartbeat',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['venus'] = array("class"=>'venus',"tags"=>'venus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mars'] = array("class"=>'mars',"tags"=>'mars',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mercury'] = array("class"=>'mercury',"tags"=>'mercury',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['intersex, transgender'] = array("class"=>'intersex transgender',"tags"=>'intersex,transgender',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['transgender-alt'] = array("class"=>'transgender-alt',"tags"=>'transgender-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['venus-double'] = array("class"=>'venus-double',"tags"=>'venus-double',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mars-double'] = array("class"=>'mars-double',"tags"=>'mars-double',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['venus-mars'] = array("class"=>'venus-mars',"tags"=>'venus-mars',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mars-stroke'] = array("class"=>'mars-stroke',"tags"=>'mars-stroke',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mars-stroke-v'] = array("class"=>'mars-stroke-v',"tags"=>'mars-stroke-v',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mars-stroke-h'] = array("class"=>'mars-stroke-h',"tags"=>'mars-stroke-h',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['neuter'] = array("class"=>'neuter',"tags"=>'neuter',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['genderless'] = array("class"=>'genderless',"tags"=>'genderless',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['facebook-official'] = array("class"=>'facebook-official',"tags"=>'facebook-official',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pinterest-p'] = array("class"=>'pinterest-p',"tags"=>'pinterest-p',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['whatsapp'] = array("class"=>'whatsapp',"tags"=>'whatsapp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['server'] = array("class"=>'server',"tags"=>'server',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-plus'] = array("class"=>'user-plus',"tags"=>'user-plus',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-times'] = array("class"=>'user-times',"tags"=>'user-times',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bed, hotel'] = array("class"=>'bed hotel',"tags"=>'bed,hotel',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['viacoin'] = array("class"=>'viacoin',"tags"=>'viacoin',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['train'] = array("class"=>'train',"tags"=>'train',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['subway'] = array("class"=>'subway',"tags"=>'subway',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['medium'] = array("class"=>'medium',"tags"=>'medium',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['y-combinator, yc'] = array("class"=>'y-combinator yc',"tags"=>'y-combinator,yc',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['optin-monster'] = array("class"=>'optin-monster',"tags"=>'optin-monster',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['opencart'] = array("class"=>'opencart',"tags"=>'opencart',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['expeditedssl'] = array("class"=>'expeditedssl',"tags"=>'expeditedssl',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['battery, battery-4, battery-full'] = array("class"=>'battery battery-4 battery-full',"tags"=>'battery,battery-4,battery-full',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['battery-3, battery-three-quarters'] = array("class"=>'battery-3 battery-three-quarters',"tags"=>'battery-3,battery-three-quarters',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['battery-2, battery-half'] = array("class"=>'battery-2 battery-half',"tags"=>'battery-2,battery-half',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['battery-1, battery-quarter'] = array("class"=>'battery-1 battery-quarter',"tags"=>'battery-1,battery-quarter',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['battery-0, battery-empty'] = array("class"=>'battery-0 battery-empty',"tags"=>'battery-0,battery-empty',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mouse-pointer'] = array("class"=>'mouse-pointer',"tags"=>'mouse-pointer',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['i-cursor'] = array("class"=>'i-cursor',"tags"=>'i-cursor',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['object-group'] = array("class"=>'object-group',"tags"=>'object-group',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['object-ungroup'] = array("class"=>'object-ungroup',"tags"=>'object-ungroup',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sticky-note'] = array("class"=>'sticky-note',"tags"=>'sticky-note',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sticky-note-o'] = array("class"=>'sticky-note-o',"tags"=>'sticky-note-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-jcb'] = array("class"=>'cc-jcb',"tags"=>'cc-jcb',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['cc-diners-club'] = array("class"=>'cc-diners-club',"tags"=>'cc-diners-club',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['clone'] = array("class"=>'clone',"tags"=>'clone',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['balance-scale'] = array("class"=>'balance-scale',"tags"=>'balance-scale',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hourglass-o'] = array("class"=>'hourglass-o',"tags"=>'hourglass-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hourglass-1, hourglass-start'] = array("class"=>'hourglass-1 hourglass-start',"tags"=>'hourglass-1,hourglass-start',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hourglass-2, hourglass-half'] = array("class"=>'hourglass-2 hourglass-half',"tags"=>'hourglass-2,hourglass-half',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hourglass-3, hourglass-end'] = array("class"=>'hourglass-3 hourglass-end',"tags"=>'hourglass-3,hourglass-end',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hourglass'] = array("class"=>'hourglass',"tags"=>'hourglass',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-grab-o, hand-rock-o'] = array("class"=>'hand-grab-o hand-rock-o',"tags"=>'hand-grab-o,hand-rock-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-paper-o, hand-stop-o'] = array("class"=>'hand-paper-o hand-stop-o',"tags"=>'hand-paper-o,hand-stop-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-scissors-o'] = array("class"=>'hand-scissors-o',"tags"=>'hand-scissors-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-lizard-o'] = array("class"=>'hand-lizard-o',"tags"=>'hand-lizard-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-spock-o'] = array("class"=>'hand-spock-o',"tags"=>'hand-spock-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-pointer-o'] = array("class"=>'hand-pointer-o',"tags"=>'hand-pointer-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hand-peace-o'] = array("class"=>'hand-peace-o',"tags"=>'hand-peace-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['trademark'] = array("class"=>'trademark',"tags"=>'trademark',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['registered'] = array("class"=>'registered',"tags"=>'registered',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['creative-commons'] = array("class"=>'creative-commons',"tags"=>'creative-commons',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gg'] = array("class"=>'gg',"tags"=>'gg',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gg-circle'] = array("class"=>'gg-circle',"tags"=>'gg-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['tripadvisor'] = array("class"=>'tripadvisor',"tags"=>'tripadvisor',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['odnoklassniki'] = array("class"=>'odnoklassniki',"tags"=>'odnoklassniki',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['odnoklassniki-square'] = array("class"=>'odnoklassniki-square',"tags"=>'odnoklassniki-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['get-pocket'] = array("class"=>'get-pocket',"tags"=>'get-pocket',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wikipedia-w'] = array("class"=>'wikipedia-w',"tags"=>'wikipedia-w',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['safari'] = array("class"=>'safari',"tags"=>'safari',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['chrome'] = array("class"=>'chrome',"tags"=>'chrome',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['firefox'] = array("class"=>'firefox',"tags"=>'firefox',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['opera'] = array("class"=>'opera',"tags"=>'opera',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['internet-explorer'] = array("class"=>'internet-explorer',"tags"=>'internet-explorer',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['television, tv'] = array("class"=>'television tv',"tags"=>'television,tv',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['contao'] = array("class"=>'contao',"tags"=>'contao',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['500px'] = array("class"=>'500px',"tags"=>'500px',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['amazon'] = array("class"=>'amazon',"tags"=>'amazon',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar-plus-o'] = array("class"=>'calendar-plus-o',"tags"=>'calendar-plus-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar-minus-o'] = array("class"=>'calendar-minus-o',"tags"=>'calendar-minus-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar-times-o'] = array("class"=>'calendar-times-o',"tags"=>'calendar-times-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['calendar-check-o'] = array("class"=>'calendar-check-o',"tags"=>'calendar-check-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['industry'] = array("class"=>'industry',"tags"=>'industry',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['map-pin'] = array("class"=>'map-pin',"tags"=>'map-pin',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['map-signs'] = array("class"=>'map-signs',"tags"=>'map-signs',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['map-o'] = array("class"=>'map-o',"tags"=>'map-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['map'] = array("class"=>'map',"tags"=>'map',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['commenting'] = array("class"=>'commenting',"tags"=>'commenting',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['commenting-o'] = array("class"=>'commenting-o',"tags"=>'commenting-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['houzz'] = array("class"=>'houzz',"tags"=>'houzz',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['vimeo'] = array("class"=>'vimeo',"tags"=>'vimeo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['black-tie'] = array("class"=>'black-tie',"tags"=>'black-tie',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fonticons'] = array("class"=>'fonticons',"tags"=>'fonticons',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['reddit-alien'] = array("class"=>'reddit-alien',"tags"=>'reddit-alien',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['edge'] = array("class"=>'edge',"tags"=>'edge',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['credit-card-alt'] = array("class"=>'credit-card-alt',"tags"=>'credit-card-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['codiepie'] = array("class"=>'codiepie',"tags"=>'codiepie',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['modx'] = array("class"=>'modx',"tags"=>'modx',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fort-awesome'] = array("class"=>'fort-awesome',"tags"=>'fort-awesome',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['usb'] = array("class"=>'usb',"tags"=>'usb',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['product-hunt'] = array("class"=>'product-hunt',"tags"=>'product-hunt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['mixcloud'] = array("class"=>'mixcloud',"tags"=>'mixcloud',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['scribd'] = array("class"=>'scribd',"tags"=>'scribd',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pause-circle'] = array("class"=>'pause-circle',"tags"=>'pause-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pause-circle-o'] = array("class"=>'pause-circle-o',"tags"=>'pause-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stop-circle'] = array("class"=>'stop-circle',"tags"=>'stop-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['stop-circle-o'] = array("class"=>'stop-circle-o',"tags"=>'stop-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shopping-bag'] = array("class"=>'shopping-bag',"tags"=>'shopping-bag',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shopping-basket'] = array("class"=>'shopping-basket',"tags"=>'shopping-basket',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['hashtag'] = array("class"=>'hashtag',"tags"=>'hashtag',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bluetooth'] = array("class"=>'bluetooth',"tags"=>'bluetooth',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bluetooth-b'] = array("class"=>'bluetooth-b',"tags"=>'bluetooth-b',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['percent'] = array("class"=>'percent',"tags"=>'percent',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['gitlab'] = array("class"=>'gitlab',"tags"=>'gitlab',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wpbeginner'] = array("class"=>'wpbeginner',"tags"=>'wpbeginner',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wpforms'] = array("class"=>'wpforms',"tags"=>'wpforms',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envira'] = array("class"=>'envira',"tags"=>'envira',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['universal-access'] = array("class"=>'universal-access',"tags"=>'universal-access',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wheelchair-alt'] = array("class"=>'wheelchair-alt',"tags"=>'wheelchair-alt',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['question-circle-o'] = array("class"=>'question-circle-o',"tags"=>'question-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['blind'] = array("class"=>'blind',"tags"=>'blind',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['audio-description'] = array("class"=>'audio-description',"tags"=>'audio-description',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['volume-control-phone'] = array("class"=>'volume-control-phone',"tags"=>'volume-control-phone',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['braille'] = array("class"=>'braille',"tags"=>'braille',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['assistive-listening-systems'] = array("class"=>'assistive-listening-systems',"tags"=>'assistive-listening-systems',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['american-sign-language-interpreting, asl-interpreting'] = array("class"=>'american-sign-language-interpreting asl-interpreting',"tags"=>'american-sign-language-interpreting,asl-interpreting',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['deaf, deafness, hard-of-hearing'] = array("class"=>'deaf deafness hard-of-hearing',"tags"=>'deaf,deafness,hard-of-hearing',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['glide'] = array("class"=>'glide',"tags"=>'glide',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['glide-g'] = array("class"=>'glide-g',"tags"=>'glide-g',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['sign-language, signing'] = array("class"=>'sign-language signing',"tags"=>'sign-language,signing',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['low-vision'] = array("class"=>'low-vision',"tags"=>'low-vision',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['viadeo'] = array("class"=>'viadeo',"tags"=>'viadeo',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['viadeo-square'] = array("class"=>'viadeo-square',"tags"=>'viadeo-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['snapchat'] = array("class"=>'snapchat',"tags"=>'snapchat',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['snapchat-ghost'] = array("class"=>'snapchat-ghost',"tags"=>'snapchat-ghost',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['snapchat-square'] = array("class"=>'snapchat-square',"tags"=>'snapchat-square',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['pied-piper'] = array("class"=>'pied-piper',"tags"=>'pied-piper',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['first-order'] = array("class"=>'first-order',"tags"=>'first-order',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['yoast'] = array("class"=>'yoast',"tags"=>'yoast',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['themeisle'] = array("class"=>'themeisle',"tags"=>'themeisle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['google-plus-circle, google-plus-official'] = array("class"=>'google-plus-circle google-plus-official',"tags"=>'google-plus-circle,google-plus-official',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['fa, font-awesome'] = array("class"=>'fa font-awesome',"tags"=>'fa,font-awesome',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['handshake-o'] = array("class"=>'handshake-o',"tags"=>'handshake-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envelope-open'] = array("class"=>'envelope-open',"tags"=>'envelope-open',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['envelope-open-o'] = array("class"=>'envelope-open-o',"tags"=>'envelope-open-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['linode'] = array("class"=>'linode',"tags"=>'linode',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['address-book'] = array("class"=>'address-book',"tags"=>'address-book',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['address-book-o'] = array("class"=>'address-book-o',"tags"=>'address-book-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['address-card, vcard'] = array("class"=>'address-card vcard',"tags"=>'address-card,vcard',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['address-card-o, vcard-o'] = array("class"=>'address-card-o vcard-o',"tags"=>'address-card-o,vcard-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-circle'] = array("class"=>'user-circle',"tags"=>'user-circle',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-circle-o'] = array("class"=>'user-circle-o',"tags"=>'user-circle-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['user-o'] = array("class"=>'user-o',"tags"=>'user-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['id-badge'] = array("class"=>'id-badge',"tags"=>'id-badge',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['drivers-license, id-card'] = array("class"=>'drivers-license id-card',"tags"=>'drivers-license,id-card',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['drivers-license-o, id-card-o'] = array("class"=>'drivers-license-o id-card-o',"tags"=>'drivers-license-o,id-card-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['quora'] = array("class"=>'quora',"tags"=>'quora',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['free-code-camp'] = array("class"=>'free-code-camp',"tags"=>'free-code-camp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['telegram'] = array("class"=>'telegram',"tags"=>'telegram',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thermometer, thermometer-4, thermometer-full'] = array("class"=>'thermometer thermometer-4 thermometer-full',"tags"=>'thermometer,thermometer-4,thermometer-full',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thermometer-3, thermometer-three-quarters'] = array("class"=>'thermometer-3 thermometer-three-quarters',"tags"=>'thermometer-3,thermometer-three-quarters',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thermometer-2, thermometer-half'] = array("class"=>'thermometer-2 thermometer-half',"tags"=>'thermometer-2,thermometer-half',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thermometer-1, thermometer-quarter'] = array("class"=>'thermometer-1 thermometer-quarter',"tags"=>'thermometer-1,thermometer-quarter',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['thermometer-0, thermometer-empty'] = array("class"=>'thermometer-0 thermometer-empty',"tags"=>'thermometer-0,thermometer-empty',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['shower'] = array("class"=>'shower',"tags"=>'shower',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bath, bathtub, s15'] = array("class"=>'bath bathtub s15',"tags"=>'bath,bathtub,s15',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['podcast'] = array("class"=>'podcast',"tags"=>'podcast',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['window-maximize'] = array("class"=>'window-maximize',"tags"=>'window-maximize',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['window-minimize'] = array("class"=>'window-minimize',"tags"=>'window-minimize',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['window-restore'] = array("class"=>'window-restore',"tags"=>'window-restore',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['times-rectangle, window-close'] = array("class"=>'times-rectangle window-close',"tags"=>'times-rectangle,window-close',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['times-rectangle-o, window-close-o'] = array("class"=>'times-rectangle-o window-close-o',"tags"=>'times-rectangle-o,window-close-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['bandcamp'] = array("class"=>'bandcamp',"tags"=>'bandcamp',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['grav'] = array("class"=>'grav',"tags"=>'grav',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['etsy'] = array("class"=>'etsy',"tags"=>'etsy',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['imdb'] = array("class"=>'imdb',"tags"=>'imdb',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['ravelry'] = array("class"=>'ravelry',"tags"=>'ravelry',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['eercast'] = array("class"=>'eercast',"tags"=>'eercast',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['microchip'] = array("class"=>'microchip',"tags"=>'microchip',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['snowflake-o'] = array("class"=>'snowflake-o',"tags"=>'snowflake-o',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['superpowers'] = array("class"=>'superpowers',"tags"=>'superpowers',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['wpexplorer'] = array("class"=>'wpexplorer',"tags"=>'wpexplorer',"unicode"=>'');
$icons['icomoon-font-awesome-14x14']['meetup'] = array("class"=>'meetup',"tags"=>'meetup',"unicode"=>'');